version: '3'
networks:
  dev-network:
    external: true

services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./tmp/minio:/data
    ports:
      - 9000:9000
    networks:
      - dev-network
    command: server /data
  minio_bucket:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - PROJECT_BUCKET=${IMG}
    volumes:
    - ./scripts:/work_dir
    working_dir: /work_dir
    entrypoint: /bin/bash
    command:  ./minio_create_bucket.sh
    networks:
      - dev-network
