version: '3'
networks:
  dev-network:
    external: true

services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./tmp/minio:/data
    ports:
      - 9000:9000
    networks:
      - dev-network
    command: server /data

# Создание бакета для данных
  minio_bucket_data:
    image: minio/mc
    container_name: minio_create_bucket_data
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - PROJECT_BUCKET=${IMG}/data
    volumes:
    - ./scripts:/work_dir
    working_dir: /work_dir
    entrypoint: /bin/bash
    command:  ./minio_create_bucket.sh
    networks:
      - dev-network

# Создание бакета для моделей
  minio_bucket_models:
    image: minio/mc
    container_name: minio_create_bucket_models
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - PROJECT_BUCKET=${IMG}/models
    volumes:
    - ./scripts:/work_dir
    working_dir: /work_dir
    entrypoint: /bin/bash
    command:  ./minio_create_bucket.sh
    networks:
      - dev-network

  mlflow_server:
    depends_on:
      - minio_bucket_models
      - mysql
    build: build/mlflow-server
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_BUCKET=${IMG}:/models
      - MYSQL_DATABASE=mlflow
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    networks:
      - dev-network
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mlflow
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
    networks:
      - dev-network
